[package]
name = "intspan"
version = "0.1.0"
authors = ["wang-q <wang-q@outlook.com>"]
license = "MIT"
edition = "2018"
description = "`IntSpan` handles of sets containing integer spans"

[lib]
name = "intspan"

[[bin]]
name = "intspan-bin"
path = "src/bin.rs"

[[example]]
name = "benchmark"

[[example]]
name = "file"

[dependencies]
