[package]
name = "intspan"
version = "0.2.0"
authors = ["wang-q <wang-q@outlook.com>"]
description = "`IntSpan` handles of sets containing integer spans"
documentation = "https://github.com/wang-q/intspan"
homepage = "https://github.com/wang-q/intspan"
repository = "https://github.com/wang-q/intspan"
readme = "README.md"
categories = ["command-line-utilities", "text-processing"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "wang-q/intspan", branch="0.2.0" }
appveyor = { repository = "wang-q/intspan" }

[lib]
name = "intspan"

[[bin]]
name = "intspan"
path = "src/main.rs"

[[example]]
name = "benchmark"

[[example]]
name = "file"

[dependencies]
clap = "2"
serde = "1.0"
serde_yaml = "0.8"
regex = "1"
lazy_static = "1.3.0"

[build-dependencies]

[dev-dependencies]
tempfile = "3.1.0"
assert_cmd = "0.11"
predicates = "1"
